### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by robouden** [lvgl/lvgl_editor#1]
Small spelling mistake in the README file:

Custom widget creation: Unlike components, widgets have C logic. You can recompile the editor to make it contain the new **wodgets'** code.

Should be:
Custom widget creation: Unlike components, widgets have C logic. You can recompile the editor to make it contain the new **widgets'** code.

**Comment by kisvegabor** [comment]
Thank you for opening the first issue here. We will remember this moment when we close the 1000th issue. :smile: 


I've just fixed the typo.
